# Generated by Django 5.2.5 on 2025-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_courselike_course_liked_by_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='users', to='courses.course'),
        ),
    ]
