# Generated by Django 5.2.4 on 2025-08-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WatchProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('course_id', models.IntegerField()),
                ('chapter_id', models.IntegerField()),
                ('current_time', models.FloatField(default=0)),
                ('total_duration', models.FloatField(default=0)),
                ('watched_percentage', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('total_watch_time', models.FloatField(default=0)),
                ('session_count', models.IntegerField(default=0)),
                ('watch_speed', models.FloatField(default=1.0)),
                ('first_watched_at', models.DateTimeField(auto_now_add=True)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'course_id'], name='watch_watch_user_id_1177e6_idx'), models.Index(fields=['user_id', 'chapter_id'], name='watch_watch_user_id_e48bdc_idx')],
                'unique_together': {('user_id', 'course_id', 'chapter_id')},
            },
        ),
    ]
