# Generated by Django 5.2.4 on 2025-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='watchprogress',
            name='watch_watch_user_id_1177e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchprogress',
            name='watch_watch_user_id_e48bdc_idx',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='chapter_id',
            new_name='chapterId',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='completed_at',
            new_name='completedAt',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='course_id',
            new_name='courseId',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='current_time',
            new_name='currentTime',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='first_watched_at',
            new_name='firstWatchedAt',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='is_completed',
            new_name='isCompleted',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='last_watched_at',
            new_name='lastWatchedAt',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='session_count',
            new_name='sessionCount',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='total_duration',
            new_name='totalDuration',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='total_watch_time',
            new_name='totalWatchTime',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='user_id',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='watch_speed',
            new_name='watchSpeed',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='watched_percentage',
            new_name='watchedPercentage',
        ),
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together={('userId', 'courseId', 'chapterId')},
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['userId', 'courseId'], name='watch_watch_userId_ee55f5_idx'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['userId', 'chapterId'], name='watch_watch_userId_c72726_idx'),
        ),
    ]
