# Generated by Django 5.2.4 on 2025-08-12 04:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_remove_watchprogress_watch_watch_user_id_1177e6_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='watchprogress',
            name='watch_watch_userId_ee55f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='watchprogress',
            name='watch_watch_userId_c72726_idx',
        ),
        migrations.RenameField(
            model_name='watchprogress',
            old_name='courseId',
            new_name='videoId',
        ),
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='chapterOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='courseId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='lastChapterIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='lastVideoIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='videoOrder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='watchprogress',
            unique_together={('userId', 'courseId', 'chapterId', 'videoId')},
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['userId', 'courseId'], name='watch_watch_userId_ad602a_idx'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['userId', 'courseId', 'chapterOrder'], name='watch_watch_userId_722ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='watchprogress',
            index=models.Index(fields=['userId', 'courseId', 'chapterOrder', 'videoOrder'], name='watch_watch_userId_37ff50_idx'),
        ),
    ]
