# Generated by Django 5.2.4 on 2025-08-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_remove_watchprogress_watch_watch_userid_ee55f5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchprogress',
            new_name='watch_watch_userId_ee55f5_idx',
            old_name='watch_watch_userId_ad602a_idx',
        ),
        migrations.RenameIndex(
            model_name='watchprogress',
            new_name='watch_watch_userId_3be30d_idx',
            old_name='watch_watch_userId_722ad2_idx',
        ),
        migrations.RenameIndex(
            model_name='watchprogress',
            new_name='watch_watch_userId_664dd4_idx',
            old_name='watch_watch_userId_37ff50_idx',
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='chapterIndex',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='watchprogress',
            name='videoIndex',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='courseId',
            field=models.IntegerField(),
        ),
    ]
