# Generated by Django 5.2.4 on 2025-08-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_rename_watch_watch_userid_ad602a_idx_watch_watch_userid_ee55f5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=100)),
                ('courseId', models.IntegerField()),
                ('lastChapterId', models.IntegerField()),
                ('lastVideoId', models.IntegerField()),
                ('lastChapterOrder', models.IntegerField(default=0)),
                ('lastVideoOrder', models.IntegerField(default=0)),
                ('lastChapterIndex', models.IntegerField(default=1)),
                ('lastVideoIndex', models.IntegerField(default=1)),
                ('lastWatchedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('userId', 'courseId')},
            },
        ),
    ]
