# Generated by Django 5.2.4 on 2025-08-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_userlastwatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlastwatched',
            name='chapterId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlastwatched',
            name='videoId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='chapterId',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='courseId',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='videoId',
            field=models.IntegerField(db_index=True),
        ),
    ]
