# Generated by Django 5.2.4 on 2025-08-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_userlastwatched_chapterid_userlastwatched_videoid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlastwatched',
            name='lastCurrentTime',
            field=models.FloatField(default=0.0),
        ),
    ]
