# Generated by Django 5.2.5 on 2025-08-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='instructor_profiles/'),
        ),
    ]
