# Generated by Django 5.2.5 on 2025-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_active_instructor_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order_index', 'chapter_id']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order_index', 'course_id']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order_index', 'video_id']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='order',
        ),
        migrations.RemoveField(
            model_name='video',
            name='order',
        ),
        migrations.AddField(
            model_name='chapter',
            name='order_index',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='order_index',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='order_index',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('course', 'order_index'), name='uniq_chapter_order_per_course'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('chapter', 'order_index'), name='uniq_video_order_per_chapter'),
        ),
    ]
