# Generated by Django 5.2.5 on 2025-08-12 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_chapter_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_type',
            field=models.CharField(choices=[('free', '무료'), ('paid', '유료'), ('gov', '국비')], default='paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.chapter'),
        ),
        migrations.AlterField(
            model_name='video',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.course'),
        ),
    ]
