# Generated by Django 5.2.5 on 2025-08-12 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price_type_alter_video_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='5자리 정수 코드(자동 발급)', null=True, unique=True, validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(99999)]),
        ),
    ]
