# Generated by Django 5.2.5 on 2025-08-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='english_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
