# Generated by Django 5.2.5 on 2025-08-13 05:55

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_enrollment_course_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'mkv', 'webm', 'avi']), courses.models.validate_file_size]),
        ),
    ]
