# Generated by Django 5.2.5 on 2025-08-13 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_video_video_url_video_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', through='courses.CourseLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courselike',
            index=models.Index(fields=['user', 'course'], name='courses_cou_user_id_fac34a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courselike',
            unique_together={('user', 'course')},
        ),
    ]
