# Generated by Django 5.2.4 on 2025-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('problem_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('user_code', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('email', 'problem_id')},
            },
        ),
    ]
